name: Build and Publish Nuget Package
run-name: ${{ github.actor }}

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

concurrency:
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: true

jobs:
    build:
        runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[0] }}
        timeout-minutes: 60
        strategy:
          matrix:
            dotnet-version: ['7.0.x']

        steps:
            - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
            - uses: actions/checkout@v3

            - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: ${{ matrix.dotnet-version }}

            
            - uses: actions/cache@v3
              with:
                path: ~/.nuget/packages
                key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-nuget

            - name: Install dependencies
              run: dotnet restore
            
            - name: Build
              run: dotnet build --configuration Release --no-restore

            - name: Build the NuGet package
              run: cd ./EditorConfig && dotnet pack --configuration Release --output ./Package

            - name: Publish NuGet Package
              run: pwd

            

            
